### ISSUE TITLE
Details of production environment - Atlas of Living Scotland

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/documentation#16]

**Comment by djtfmartin** [comment]
![ala architecture - paris workshop - may 2015](https://cloud.githubusercontent.com/assets/444897/12416212/fea5eee8-be97-11e5-999f-c1baf6927b36.jpg)

**Comment by aruizca** [comment]
@nickdos The diagram above should be in the WIKI :-) Not sure if @djtfmartin is aware of the WIKI (https://jingo.ala.org.au). My idea was to include info of the main core systems (functional info + technical overview) in the business section. Deep technical details should still be in each project README.md or GH WIKI

**Comment by nickdos** [comment]
Good idea - @djtfmartin  has been updating the Jingo wiki so he knows about it. There is no architecture page that I could see - sounds like a good opportunity to create one... Once the ALS stuff is out of the way Dave, it might be a nice distraction to put up an architecture section/page on the wiki or else simply have a landing page that then points to the relevant pages on this repo?

**Comment by djtfmartin** [comment]
Is the wiki public at all (without login) ?  
The intention here is to share deployment and installation information with other countries.
We are an open source project, so putting this information behind a login doesn't seem the best way to go.

FYI - the documentation is here: https://github.com/AtlasOfLivingAustralia/documentation/wiki with the deployments from other countries.

We also have contributions coming from the other countries (see the issue tracker).
