### ISSUE TITLE
Details of production environment - GBIF Spain

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/documentation#20]

**Comment by santiagomtzdelariva** [comment]
![image](https://cloud.githubusercontent.com/assets/3853645/12390734/ef758a88-bde2-11e5-9859-7eefb2f8e1ec.png)

**Comment by santiagomtzdelariva** [comment]
That is the current production environment of GBIF Spain, we dont have in this moment done the connection between the image server and generic-hub module,  but our idea is that we can show the images stored in this server through the generic-hub module in the images tab.

**Comment by djtfmartin** [comment]
Added here: 

https://github.com/AtlasOfLivingAustralia/documentation/wiki/Gbif-Spain-Production-environment
