### ISSUE TITLE
Details of production environment - Brazil

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/documentation#22]

**Comment by eugeniob** [comment]
## **Virtual Machine Settings**

### Memory

**qtd memory:** 32Gb
**qtd memory JVM:** 23Gb
**free Space on Disk:** 17 Gb

### System Environment

**java.vendor:** Oracle Corporation 
**sun.java.launcher:** SUN_STANDARD 
**catalina.base:** /opt/apache-tomcat-6.0.41 
**sun.management.compiler:** HotSpot 64-Bit Tiered Compilers 
**catalina.useNaming:** true 
**os.name:** Linux 
**java.vm.specification.vendor:** Oracle Corporation 
**java.runtime.version:** 1.7.0_85-mockbuild_2015_07_25_13_10-b00 
**grails.env.initializing:** false 
**tomcat.util.buf.StringCache.byte.enabled:** true 
**java.naming.factory.initial:** org.apache.naming.java.javaURLContextFactory 
**user.language:** en 
**java.version:** 1.7.0_85 
**java.util.logging.manager:** org.apache.juli.ClassLoaderLogManager 
**user.timezone:** America/Sao_Paulo 
**sun.arch.data.model:** 64 
**sun.cpu.isalist:** sun.jnu.encoding UTF-8 
**file.encoding.pkg:** sun.io 
**package.access:** sun.,org.apache.catalina.,org.apache.coyote.,org.apache.jasper.,org.apache.naming.resources.,org.apache.tomcat.,sun.beans. 
**file.separator:** / 
**java.specification.name:** Java Platform API Specification 
**java.class.version:** 51.0 
**user.country:** US 
**java.vm.info:** mixed mode 
**os.version:** 2.6.32-573.1.1.el6.x86_64 
**sun.font.fontmanager:** sun.awt.X11FontManager 
**path.separator:** : 
**javax.accessibility.assistive_technologies:** org.GNOME.Accessibility.JavaBridge 
**java.vm.version:** 24.85-b03 
**java.awt.printerjob:** sun.print.PSPrinterJob 
**sun.io.unicode.encoding:** UnicodeLittle 
**awt.toolkit:** sun.awt.X11.XToolkit 
**package.definition:** sun.,java.,org.apache.catalina.,org.apache.coyote.,org.apache.jasper.,org.apache.naming.,org.apache.tomcat. 
**java.naming.factory.url.pkgs:** org.apache.naming 
**java.specification.vendor:** Oracle Corporation 
**java.vendor.url:** http://java.oracle.com/ 
**net.sf.ehcache.skipUpdateCheck:** true 
**java.vm.vendor:** Oracle Corporation 
**java.runtime.name:** OpenJDK Runtime Environment 
**sun.java.command:** org.apache.catalina.startup.Bootstrap start 
**java.vm.specification.name:** Java Virtual Machine Specification 
**java.vm.specification.version:** 1.7 
**sun.cpu.endian:** little 
**java.vendor.url.bug:** http://bugreport.sun.com/bugreport/ 
**os.arch:** amd64 
**java.awt.graphicsenv:** sun.awt.X11GraphicsEnvironment 
**line.separator:** 
**java.vm.name:** OpenJDK 64-Bit Server VM 
**file.encoding:** UTF-8 
**java.specification.version:** 1.7

**Comment by eugeniob** [comment]
David, if you need any further information or have any suggestions to improve our environment, let me know.

**Comment by djtfmartin** [comment]
I've actually only just seen this message. Is everything installed on that one machine ?

If you are using several machines, an deployment diagram would help.

**Comment by eugeniob** [comment]
Yes, we are currently using a single VM, but we plan to separate the services soon. By the way, 
could you send me that machines diagram, you show me at the meeting ?

**Comment by djtfmartin** [comment]
ok - sending an email.
